site_name: LunarPhaseORM Documentation
site_description: Technical manual and documentation for LunarPhaseORM Python & Rust hybrid ORM.
site_author: LunarPy-Labs

repo_name: LunarPy-Labs/LunarPhaseORM
repo_url: https://github.com/LunarPy-Labs/LunarPhaseORM

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
    - scheme: default
      primary: indigo
      accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - footnotes
  - admonition

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Syntax Cheat Sheet: syntax-cheatsheet.md
  - Core Architecture: architecture.md
  - Models & Fields: models-and-fields.md
  - Query Builder: query-builder.md
  - Relations & Auto-Batching: relations-and-batching.md
  - Unit of Work & Transactions: unit-of-work.md
  - Migrations & CLI: migrations-cli.md
